import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gql } from "@apollo/client";
import client from "../apollo-client";
import Link from 'next/link';
import PageBlocks  from '../components/PageBlocks';
import Stats  from '../components/Stats';
import Nav  from '../components/Nav';
import { getPostAndMorePosts } from './../lib/api';

export default function Page({ singlePost, slug }) {
    console.log(slug);
    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav />
        <PageBlocks content={singlePost['pageBlocks']} />
        <Stats />
      </main>
     
    </div>
  )
}

export async function getServerSideProps(context) {
  const { slug } = context.query
  const data = await getPostAndMorePosts(slug);

  return {
      props: { 
        singlePost: data.entry,
        slug: slug
      }
  };
}