import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import PageBlocks  from '../components/PageBlocks';
import Stats  from '../components/Stats';
import Nav  from '../components/Nav';
import { getPostAndMorePosts } from './../lib/api'

export default function Page({ entry }) {
    console.log(entry);
    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav />
        <PageBlocks content={entry['pageBlocks']} />
        <Stats />
      </main>
     
    </div>
  )
}


export async function getServerSideProps(context) {
  const { slug } = context.query
  const data = await getPostAndMorePosts(slug);

  return {
      props: { 
          entry: data.entry,
          currentPage: "1",
      }
  };
}

