import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { getAllPostsForHome } from './../lib/api'

export default function Home({ allPosts }) {
  // console.log(allPosts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Stuff will go here</p>
        <ul>
        {allPosts.map((post, i) => {
          return(
            <li key={i}><Link href={`/${post.slug}`}><a>{post.title} - {post.__typename} - {post.slug} - {post.id}</a></Link></li>
          )
        })}
        </ul>

      </main>

     
    </div>
  )
}

export async function getServerSideProps(context) {
  const { slug } = context.query
  const data = await getAllPostsForHome(slug);

  return {
      props: { 
          allPosts: data.entries,
          currentPage: "1",
      }
  };
}